# Imports

In [1]:
import numpy
from numpy import arange
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from joblib import dump
from joblib import load
import pickle

# Crear modelo

## Descargar dataset

In [2]:
dataset = pd.read_csv('/home/user/machinelearning/imida/data/AL41_valores_imputados.csv')
dataset.head()

FECHA CODEST  VVMED  VVMAX  RVIENTO   DVMED   TMIN   TMAX   TMED  \
0  23/04/2010   AL41   1.51   8.23   130.06  145.15   9.74  21.44  16.07   
1  24/04/2010   AL41   1.64   8.13   141.92  176.62  10.79  25.06  17.78   
2  25/04/2010   AL41   1.54   8.43   132.96   94.79  11.79  24.97  17.31   
3  26/04/2010   AL41   1.75   9.11   151.19  130.98   8.98  25.68  17.27   
4  27/04/2010   AL41   1.92  10.19   165.98  174.00   8.59  28.48  18.05   

   TMINABS  ...  HSOL  PREC  HORAS0  HORAS7  DEWPT   DPV  ETO_PM_FAO  \
0    9.250  ...  11.0   0.1     0.0     0.0  12.41  0.51    3.010548   
1   10.330  ...  12.0   0.0     0.0     0.0  11.81  0.74    4.496808   
2   11.330  ...  10.0   0.0     0.0     0.0  12.08  0.64    3.886669   
3    8.420  ...  12.0   0.0     0.0     0.0   8.83  0.96    5.082196   
4    7.913  ...  12.0   0.0     0.0     0.0   8.47  1.14    5.563509   

      FECHA_2     AÑO   ESTACION  
0  2010-04-23  2010.0  PRIMAVERA  
1  2010-04-24  2010.0  PRIMAVERA  
2  2010-04-25  2010.0  PRIMAVERA  
3  2010-04-26  2010.0  PRIMAVERA  
4  2010-04-27  2010.0  PRIMAVERA  

[5 rows x 28 columns]

## Separar dataset

In [3]:
dataset_reducido = dataset.select_dtypes(include=['float64', 'int64', 'int32'])
dataset_reducido['ESTACION'] = dataset['ESTACION']
array = dataset_reducido.values
X = array[:,0:-2]
Y = array[:,-1]
print(X)
print(Y)

[[1.51 8.23 130.06 ... 12.41 0.51 3.010548433]
 [1.64 8.13 141.92 ... 11.81 0.74 4.496808253]
 [1.54 8.43 132.96 ... 12.08 0.64 3.886668604]
 ...
 [2.8 9.6 241.88 ... 1.4 0.82 2.819171591]
 [3.84 12.54 332.07 ... 0.99 0.96 3.683019055]
 [3.05 8.7 263.77 ... 2.53 0.88 2.908153209]]
['PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA' ... 'INVIERNO' 'INVIERNO' 'INVIERNO']


## Estandarizar

In [4]:
standard_scaler = StandardScaler().fit(X)
X_estandarizado = standard_scaler.transform(X)
print(X_estandarizado)

[[-0.78218139 -0.36518946 -0.78794258 ...  0.70215484 -0.87121103
  -0.48965848]
 [-0.62288653 -0.40440915 -0.61971062 ...  0.60351245 -0.47650625
   0.1991642 ]
 [-0.74542103 -0.28675007 -0.7468066  ...  0.64790152 -0.64811702
  -0.08361141]
 ...
 [ 0.79851376  0.17212037  0.79820387 ... -1.10793295 -0.33921762
  -0.57835408]
 [ 2.07287264  1.32517941  2.07753269 ... -1.17533859 -0.09896254
  -0.17799493]
 [ 1.10485003 -0.18085689  1.10870956 ... -0.92215646 -0.23625116
  -0.53711462]]


## Separar prueba-entrenamiento

In [5]:
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = train_test_split(X_estandarizado, Y, test_size=validation_size, random_state=seed, shuffle=False)

## Valores para entrenar

In [6]:
num_folds = 10
seed = 7
scoring = 'accuracy'
kfold = KFold(n_splits=num_folds, random_state=seed, shuffle=True)

## Probar modelos

### Logistic Regression

In [7]:
result_lr = cross_val_score(LogisticRegression(max_iter=500), X_train, Y_train, cv=kfold, scoring=scoring)
print(result_lr.mean(), result_lr.std())

0.8235071328109302 0.016199433175332324


### Linear discriminant analysis

In [8]:
result_lda = cross_val_score(LinearDiscriminantAnalysis(), X_train, Y_train, cv=kfold, scoring=scoring)
print(result_lda.mean(), result_lda.std())

0.8232007233273055 0.021387794933565452


### k-nearest neighbors

In [9]:
result_knn = cross_val_score(KNeighborsClassifier(), X_train, Y_train, cv=kfold, scoring=scoring)
print(result_knn.mean(), result_knn.std())

0.8003877838055053 0.020935235453101067


/home/user/machinelearning/env/lib/python3.11/site-packages/joblib/externals/loky/backend/context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[Errno 2] No such file or directory: 'lscpu'
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "/home/user/machinelearning/env/lib/python3.11/site-packages/joblib/externals/loky/backend/context.py", line 250, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "/nix/store/mh6gqjf1w1i6ln1a61psnz0gzdmwrspl-python3-3.11.8/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/mh6gqjf1w1i6ln1a61psnz0gzdmwrspl-python3-3.11.8/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "

### Clasification tree

In [10]:
result_cart = cross_val_score(DecisionTreeClassifier(), X_train, Y_train, cv=kfold, scoring=scoring)
print(result_cart.mean(), result_cart.std())

0.7750281293952179 0.02378036645047852


### Gaussian naive Bayes

In [11]:
result_gnb = cross_val_score(GaussianNB(), X_train, Y_train, cv=kfold, scoring=scoring)
print(result_gnb.mean(), result_gnb.std())

0.662866184448463 0.024258205749805167


### Support vector machines

In [12]:
result_svc = cross_val_score(SVC(), X_train, Y_train, cv=kfold, scoring=scoring)
print(result_svc.mean(), result_svc.std())

0.822242314647378 0.01816559202969324


## Tunning

He decidido tunear el linear discriminant analysis, ya que es el que mejor resultados da junto a Logistic Regression y tarda menos que este último

In [13]:
'''
param_grid = dict(solver=['svd', 'lsqr', 'eigen'], shrinkage=[None, 'auto'], store_covariance=[True, False])
kfold = KFold(n_splits=num_folds, random_state=seed, shuffle=True)
grid = GridSearchCV(estimator=LinearDiscriminantAnalysis(), param_grid=param_grid, scoring=scoring, cv=kfold)
grid_result = grid.fit(X_train, Y_train)
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))
'''

'\nparam_grid = dict(solver=[\'svd\', \'lsqr\', \'eigen\'], shrinkage=[None, \'auto\'], store_covariance=[True, False])\nkfold = KFold(n_splits=num_folds, random_state=seed, shuffle=True)\ngrid = GridSearchCV(estimator=LinearDiscriminantAnalysis(), param_grid=param_grid, scoring=scoring, cv=kfold)\ngrid_result = grid.fit(X_train, Y_train)\nprint("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))\nmeans = grid_result.cv_results_[\'mean_test_score\']\nstds = grid_result.cv_results_[\'std_test_score\']\nparams = grid_result.cv_results_[\'params\']\nfor mean, stdev, param in zip(means, stds, params):\n    print("%f (%f) with: %r" % (mean, stdev, param))\n'

## Validar

In [14]:
model = LinearDiscriminantAnalysis(store_covariance=True)
model.fit(X_train, Y_train)
predictions = model.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.8215189873417722
[[166  54   9   0]
 [ 39 144   1   5]
 [  6  10 161   7]
 [  0   8   2 178]]
              precision    recall  f1-score   support

    INVIERNO       0.79      0.72      0.75       229
       OTOÑO       0.67      0.76      0.71       189
   PRIMAVERA       0.93      0.88      0.90       184
      VERANO       0.94      0.95      0.94       188

    accuracy                           0.82       790
   macro avg       0.83      0.83      0.83       790
weighted avg       0.83      0.82      0.82       790



# Validación

## Descargar dataset

In [15]:
df = pd.read_csv('/home/user/machinelearning/imida/data/AL41.csv', sep=';')
dataset_validacion = pd.read_csv('/home/user/machinelearning/imida/data/AL41_validation.csv', sep=';', names=df.columns)
dataset_validacion.dropna(inplace=True)
dataset_validacion.head()

CODEST       FECHA VVMED  VVMAX RVIENTO   DVMED  TMIN   TMAX   TMED TMINABS  \
0   AL41  01/01/2024  0,32  4,822   27,99   59,83  3,63  17,67   9,75   2,563   
1   AL41  02/01/2024  0,09  4,665    7,55  168,79  0,74  18,11   7,64  -0,196   
2   AL41  03/01/2024  0,15  3,744   13,15  168,93  1,92  21,51   9,58    0,92   
3   AL41  04/01/2024  0,06  4,292    4,83   32,82  6,47  17,34  12,18   5,732   
4   AL41  05/01/2024  1,97   9,45   170,4  263,44  7,52  16,55  12,27   6,798   

   ... HRMAXABS  RADMED RADMAX HSOL PREC HORAS0 HORAS7 DEWPT   DPV  \
0  ...     83,8  102,32  514,3    6    0      0      8  2,26  0,53   
1  ...       85  113,44  797,1    8    0      0     13  0,76  0,47   
2  ...     83,4  123,81  529,7    8    0      0      9  0,79  0,67   
3  ...     86,7   51,55  411,5    6    0      0      2  7,13  0,43   
4  ...     86,8   89,73  704,6    7    0      0      0  2,53  0,67   

    ETO_PM_FAO  
0  0,713398532  
1  0,422334652  
2  0,548790064  
3  0,589718576  
4  1,843253317  

[5 rows x 25 columns]

## Preparar dataset

### Floats

In [16]:
dataset_validacion.replace(',', '.', regex=True, inplace=True)
dataset_validacion = dataset_validacion.astype(str)   #Pasamos todo a String
for variable in dataset_validacion.columns:
    for x in dataset_validacion[variable]:
        if(('.' in x) or (x.isdigit())):   #Sería mejor una expresión regular del estilo [0-9]*[.][0-9]+
            #Si encontramos una variable con un punto, significa que es un float, por lo que lo pasamos a float
            dataset_validacion[variable] = dataset_validacion[variable].astype(float)
            break   #Con detectar una nos vale para cambiar toda la columna

### Fechas

In [17]:
dataset_validacion['FECHA'] = pd.to_datetime(dataset_validacion['FECHA'], format="%d/%m/%Y")
dataset_validacion.dtypes

CODEST                object
FECHA         datetime64[ns]
VVMED                float64
VVMAX                float64
RVIENTO              float64
DVMED                float64
TMIN                 float64
TMAX                 float64
TMED                 float64
TMINABS              float64
TMAXABS              float64
HRMIN                float64
HRMAX                float64
HRMED                float64
HRMINABS             float64
HRMAXABS             float64
RADMED               float64
RADMAX               float64
HSOL                 float64
PREC                 float64
HORAS0               float64
HORAS7               float64
DEWPT                float64
DPV                  float64
ETO_PM_FAO           float64
dtype: object

In [18]:
estaciones = []
for x in dataset_validacion['FECHA'].values:
    if(int(x.astype(str)[5:7]) < 3):
        estaciones.append('INVIERNO')
    elif(int(x.astype(str)[5:7]) == 3):
        if(int(x.astype(str)[8:10]) <= 20):
            estaciones.append('INVIERNO')
        else:
            estaciones.append('PRIMAVERA')
    elif(int(x.astype(str)[5:7]) < 6):
        estaciones.append('PRIMAVERA')
    elif(int(x.astype(str)[5:7]) == 6):
        if(int(x.astype(str)[8:10]) <= 20):
            estaciones.append('PRIMAVERA')
        else:
            estaciones.append('VERANO')
    elif(int(x.astype(str)[5:7]) < 9):
        estaciones.append('VERANO')
    elif(int(x.astype(str)[5:7]) == 9):
        if(int(x.astype(str)[8:10]) <= 22):
            estaciones.append('VERANO')
        else:
            estaciones.append('OTOÑO')
    elif(int(x.astype(str)[5:7]) < 12):
        estaciones.append('OTOÑO')
    else:
        if(int(x.astype(str)[8:10]) >= 22):
            estaciones.append('INVIERNO')
        else:
            estaciones.append('OTOÑO')
dataset_validacion['ESTACION'] = estaciones
dataset_validacion.tail(5)

CODEST      FECHA  VVMED   VVMAX  RVIENTO   DVMED   TMIN   TMAX   TMED  \
162   AL41 2024-06-11   1.48   6.017   127.67  333.79  16.46  24.00  19.75   
163   AL41 2024-06-12   2.82   9.760   243.99  306.15  14.98  22.59  19.38   
164   AL41 2024-06-13   2.09   8.330   180.96  343.45  13.33  25.80  19.36   
165   AL41 2024-06-14   2.02   8.430   174.91  320.70  12.74  33.07  23.40   
166   AL41 2024-06-15   2.50  11.900   216.15  334.70  17.93  33.68  24.96   

     TMINABS  ...  RADMED  RADMAX  HSOL  PREC  HORAS0  HORAS7  DEWPT   DPV  \
162    16.16  ...  136.49  1296.0   8.0   2.3     0.0     0.0  16.35  0.46   
163    14.20  ...  187.19  1404.0  10.0  12.5     0.0     0.0  15.45  0.51   
164    12.52  ...  303.16  1384.0  13.0   0.2     0.0     0.0  14.53  0.66   
165    12.02  ...  339.04  1178.0  13.0   0.0     0.0     0.0   9.28  1.88   
166    17.40  ...  307.51  1209.0  11.0   4.0     0.0     0.0  12.55  1.81   

     ETO_PM_FAO   ESTACION  
162    2.777017  PRIMAVERA  
163    3.443402  PRIMAVERA  
164    4.947626  PRIMAVERA  
165    7.061606  PRIMAVERA  
166    7.290027  PRIMAVERA  

[5 rows x 26 columns]

## Datos

In [19]:
dataset_reducido = dataset_validacion.select_dtypes(include=['float64', 'int64'])
X = dataset_reducido.values
print(X)

[[3.20000000e-01 4.82200000e+00 2.79900000e+01 ... 2.26000000e+00
  5.30000000e-01 7.13398532e-01]
 [9.00000000e-02 4.66500000e+00 7.55000000e+00 ... 7.60000000e-01
  4.70000000e-01 4.22334652e-01]
 [1.50000000e-01 3.74400000e+00 1.31500000e+01 ... 7.90000000e-01
  6.70000000e-01 5.48790064e-01]
 ...
 [2.09000000e+00 8.33000000e+00 1.80960000e+02 ... 1.45300000e+01
  6.60000000e-01 4.94762602e+00]
 [2.02000000e+00 8.43000000e+00 1.74910000e+02 ... 9.28000000e+00
  1.88000000e+00 7.06160589e+00]
 [2.50000000e+00 1.19000000e+01 2.16150000e+02 ... 1.25500000e+01
  1.81000000e+00 7.29002718e+00]]


## Target

In [21]:
Y = dataset_validacion['ESTACION'].values
print(Y)

['INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO' 'INVIERNO'
 'PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA'
 'PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA' 'PRIMAVERA' 'PRIMAV

## Escalar

In [22]:
X_estandarizado = standard_scaler.transform(X)
print(X_estandarizado)

[[-2.24034202 -1.70179668 -2.23578704 ... -0.96654553 -0.83688887
  -1.55429667]
 [-2.52217139 -1.7633716  -2.52572474 ... -1.2131515  -0.93985534
  -1.68919327]
 [-2.44865069 -2.12458499 -2.44628975 ... -1.20821938 -0.59663379
  -1.63058619]
 ...
 [-0.07148124 -0.32596976 -0.06593529 ...  1.05069127 -0.61379487
   0.40810042]
 [-0.1572554  -0.28675007 -0.15175345 ...  0.18757039  1.4798566
   1.38784653]
 [ 0.43091024  1.07417336  0.43322848 ...  0.72517139  1.35972906
   1.49371077]]


## Validar

In [23]:
predictions = model.predict(X_estandarizado)
print(accuracy_score(Y, predictions))
print(confusion_matrix(Y, predictions))
print(classification_report(Y, predictions))

0.5575757575757576
[[22 49  6  1]
 [ 0  0  0  0]
 [ 2  6 70  9]
 [ 0  0  0  0]]
              precision    recall  f1-score   support

    INVIERNO       0.92      0.28      0.43        78
       OTOÑO       0.00      0.00      0.00         0
   PRIMAVERA       0.92      0.80      0.86        87
      VERANO       0.00      0.00      0.00         0

    accuracy                           0.56       165
   macro avg       0.46      0.27      0.32       165
weighted avg       0.92      0.56      0.66       165



/home/user/machinelearning/env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/user/machinelearning/env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/user/machinelearning/env/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
